const language={
    en:{
        gpt:"GPT Search",
        signin:"Sign In",
        mainhead:"Unlimited movies, shows, and more",
        price:"Starts at ₹149. Cancel at any time.",
        enteremail:"Ready to watch? Enter your email to create or restart your membership.",
        placeholder:"Email address",
        getstarted:"Get Started ",
        morereasons:"More reasons to join",
        box1head:"Enjoy on your TV",
        box1cont:"Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.",
        box2head:"Download your shows to watch offline",
        box2cont:"Save your favourites easily and always have something to watch.",
        box3head:"Watch everywhere",
        box3cont:"Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.",
        box4head:"Create profiles for kids",
        box4cont:"Send kids on adventures with their favourite characters in a space made just for them — free with your membership.",
        faqhead:"Frequently Asked Questions",
        faq1title:"What is Netflix?",
        faq1cont:"Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries and more – on thousands of internet-connected devices.You can watch as much as you want, whenever you want, without a single ad – all for one low monthly price. There's always something new to discover, and new TV shows and movies are added every week!",
        faq2title:"How much does Netflix cost?",
        faq2cont:"Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. Plans range from ₹149 to ₹649/month.",
        faq3title:"Where can I watch?",
        faq3cont:"Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.",
        faq4title:"How do I cancel?",
        faq4cont:"Netflix is flexible. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.",
        faq5title:"What can I watch on Netflix",
        faq5cont:"Netflix has an extensive library of feature films, documentaries, shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.",
        faq6title:"Is Netflix good for kids",
        faq6cont:"The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and films in their own space.Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don’t want kids to see.",
        readytowatch:"Ready to watch? Enter your email to create or restart your membership.",
        questions:"Questions? Call",
        lastline:"This page is protected by Google reCAPTCHA to ensure you're not a bot.",
        learn:"Learn more",
        india:"Netflix India",
        faqlink:"FAQ",
        investor:"Investor Relations",
        privacy:"Privacy",
        speed:"Speed Test",
        help:"Help Center",
        job:"Jobs",
        cookie:"Cookie Preferences",
        legal:"Legal Notices",
        account:"Account",
        ways:"Ways to Watch",
        corporate:"Corporate Information",
        only:"Only on Netflix",
        media:"Media Center",
        terms:"Terms of Use",
        contact:"Contact Us"

    },
    hindi:{
        gpt:"GPT सर्च",
        signin:"साइन इन करें",
        mainhead:"अनलिमिटेड फ़िल्में, टीवी शो, और बहुत कुछ",
        price:"₹149 से शुरू। कभी भी रद्द करें।",
        enteremail:"देखने के लिए तैयार हैं? अपनी सदस्यता बनाने या पुनः शुरू करने के लिए अपना ईमेल दर्ज करें।",
        placeholder:"मेल पता",
        getstarted:"आरंभ करें ",
        morereasons:"शामिल होने के और भी कारण",
        box1head:"अपने टीवी पर आनंद लें",
        box1cont:"स्मार्ट टीवी,प्लेस्टेशन,एक्सबॉक्स, क्रोमकास्ट,एप्पल टीवी,ब्लू-रे प्लेयर और अन्य उपकरणों पर देखें।",
        box2head:"अपने शो डाउनलोड करें और उन्हें ऑफलाइन देखें",
        box2cont:"अपनी पसंदीदा सामग्री को आसानी से सेव करें और हमेशा कुछ न कुछ देखने के लिए उपलब्ध रखें।",
        box3head:"हर जगह देखें",
        box3cont:"अपने फोन, टैबलेट, लैपटॉप और टीवी पर असीमित फिल्में और टीवी शो स्ट्रीम करें।",
        box4head:"बच्चों के लिए प्रोफाइल बनाएं",
        box4cont:"अपने बच्चों को उनके पसंदीदा किरदारों के साथ रोमांचक यात्राओं पर भेजें, एक ऐसी जगह पर जो विशेष रूप से उनके लिए बनाई गई है — आपकी सदस्यता के साथ यह निःशुल्क है।",
        faqhead:"अक्सर पूछे जाने वाले प्रश्नों",
        faq1title:"क्या है Netflix?",
        faq1cont:"Netflix यह एक स्ट्रीमिंग सेवा है जो हजारों इंटरनेट-कनेक्टेड डिवाइसों पर पुरस्कार विजेता टीवी शो, फिल्में, एनीमे, वृत्तचित्र और बहुत कुछ उपलब्ध कराती है। आप जब चाहें, जितना चाहें, बिना किसी विज्ञापन के देख सकते हैं - वह भी एक कम मासिक कीमत पर। हमेशा कुछ नया देखने को मिलता है, और हर हफ्ते नए टीवी शो और फिल्में जोड़ी जाती हैं!",
        faq2title:"Netflix की कीमत कितनी है?",
        faq2cont:"Netflix अपने स्मार्टफोन, टैबलेट, स्मार्ट टीवी, लैपटॉप या स्ट्रीमिंग डिवाइस पर, एक निश्चित मासिक शुल्क पर इसका आनंद लें। प्लान ₹149 से ₹649 प्रति माह तक उपलब्ध हैं।",
        faq3title:"मैं इसे कहाँ देख सकता हूँ?",
        faq3cont:"कहीं भी, कभी भी देखें। अपने Netflix अकाउंट से साइन इन करें और अपने पर्सनल कंप्यूटर से या नेटफ्लिक्स ऐप वाले किसी भी इंटरनेट-कनेक्टेड डिवाइस पर, जैसे स्मार्ट टीवी, स्मार्टफोन, टैबलेट, स्ट्रीमिंग मीडिया प्लेयर और गेम कंसोल, netflix.com पर तुरंत वेब पर देखें।",
        faq4title:"मैं इसे रद्द कैसे करूं?",
        faq4cont:"Netflix की सुविधा लचीली है। आप दो क्लिक में आसानी से अपना खाता ऑनलाइन रद्द कर सकते हैं। कोई रद्दीकरण शुल्क नहीं है – आप अपना खाता कभी भी शुरू या बंद कर सकते हैं।",
        faq5title:"मैं Netflix पर क्या देख सकता हूँ?",
        faq5cont:"Netflix के पास फीचर फिल्मों, वृत्तचित्रों, शो, एनीमे, पुरस्कार विजेता नेटफ्लिक्स ओरिजिनल्स और बहुत कुछ का विशाल संग्रह है। जितना चाहें, जब चाहें देखें।",
        faq6title:"क्या Netflix बच्चों के लिए अच्छा है?",
        faq6cont:"आपकी सदस्यता में Netflix किड्स सुविधा शामिल है, जिससे माता-पिता बच्चों को उनके निजी स्थान पर पारिवारिक टीवी शो और फिल्मों का आनंद लेने के दौरान नियंत्रण रख सकते हैं। किड्स प्रोफाइल पिन-सुरक्षित माता-पिता नियंत्रण के साथ आते हैं, जो आपको बच्चों द्वारा देखे जाने वाले कंटेंट की परिपक्वता रेटिंग को प्रतिबंधित करने और उन विशिष्ट टाइटल्स को ब्लॉक करने की अनुमति देते हैं जिन्हें आप बच्चों को दिखाना नहीं चाहते।",
        readytowatch:"देखने के लिए तैयार हैं? अपनी मेंबरशिप बनाने या रीस्टार्ट करने के लिए अपना ईमेल एड्रेस डालें.",
        questions:"कोई सवाल? पुकारना",
        lastline:"यह पेज Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित हो सके कि आप बॉट नहीं हैं।",
        learn:"और अधिक जानें",
        india:"Netflix भारत",
        faqlink:"FAQ",
        investor:"इंवेस्टर संबंध",
        privacy:"प्रायवेसी",
        speed:"स्पीड टेस्ट",
        help:"सहायता केंद्र",
        job:"नौकरियाँ",
        cookie:"कुकी प्रेफ़रेंस",
        legal:"कानूनी नोटिस",
        account:"अकाउंट",
        ways:"देखने के तरीके",
        corporate:"कॉर्पोरेट जानकारी",
        only:"केवल Netflix पर",
        media:"मीडिया सेंटर",
        terms:"उपयोग की शर्तें",
        contact:"हमसे संपर्क करें"
    }
}

export default language;